"""
ACORD TXLife 103 Payload Formatter
====================================
Formats lead capture data into the ACORD TXLife 2.x (103 transaction type)
industry-standard payload used by insurance CRMs (e.g. Applied Epic, AgencyZoom).

This adapter ensures we build the CRM integration once in the correct format
instead of refactoring later.

Usage:
    from app.plugins.acord import format_to_txlife_103
    payload = format_to_txlife_103(lead_data)
"""

import re
import uuid
from datetime import datetime, timezone
from typing import Any


# ── PII Masking helpers ──────────────────────────────────────────────────────
_EMAIL_RE = re.compile(r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}")
_PHONE_RE = re.compile(r"(\+1[-.\s]?)?(\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4})")


def _mask_email(email: str) -> str:
    parts = email.split("@")
    if len(parts) == 2:
        first = parts[0]
        return first[0] + "***@" + parts[1] if first else "***@" + parts[1]
    return "***@***"


def _mask_phone(phone: str) -> str:
    digits = re.sub(r"\D", "", phone)
    last4 = digits[-4:] if len(digits) >= 4 else "****"
    return f"***-***-{last4}"


def _sanitize(value: str) -> str:
    """Remove HTML/script tags for safe XML embedding."""
    return re.sub(r"<[^>]+>", "", str(value)).strip()


# ── Core formatter ───────────────────────────────────────────────────────────

def format_to_txlife_103(lead_data: dict[str, Any]) -> dict[str, Any]:
    """
    Convert a raw lead capture dict into an ACORD TXLife 103 JSON payload.

    Args:
        lead_data: Dict containing keys such as:
            full_name, email, phone, zip_code,
            coverage_amount, age_range, tobacco_use,
            state, lead_score, pricing_range, session_id

    Returns:
        Dict conforming to a simplified ACORD TXLife 103 structure.
        (Full ACORD XML can be generated by wrapping this in an XML serialiser.)
    """
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    tx_id = str(uuid.uuid4()).upper()

    full_name = _sanitize(lead_data.get("full_name", "Unknown"))
    name_parts = full_name.split(" ", 1)
    first_name = name_parts[0]
    last_name = name_parts[1] if len(name_parts) > 1 else ""

    email_raw = lead_data.get("email", "")
    phone_raw = lead_data.get("phone", "")

    # Log masked values; never log raw PII
    email_masked = _mask_email(email_raw) if _EMAIL_RE.match(email_raw) else "***"
    phone_masked = _mask_phone(phone_raw) if phone_raw else "***"

    payload = {
        "TXLife": {
            "Version": "2.42.00",
            "TXLifeRequest": {
                "TransRefGUID": tx_id,
                "TransType": {
                    "tc": "103",
                    "value": "New Business Submission"
                },
                "TransSubType": {
                    "tc": "1",
                    "value": "Quote"
                },
                "OLifE": {
                    "SourceInfo": {
                        "CreatedDt": now_iso,
                        "SourceSystem": "Intermarq-AI-Chatbot",
                        "SourceSystemVersion": "MVP-1.0"
                    },
                    "Party": [
                        {
                            "id": "Party_Primary",
                            "PartyTypeCode": {"tc": "1", "value": "Person"},
                            "Person": {
                                "FirstName": first_name,
                                "LastName": last_name,
                                "Age": lead_data.get("age_range", "Unknown"),
                                "TobaccoUse": lead_data.get("tobacco_use", "No"),
                            },
                            "Address": {
                                "AddressTypeCode": {"tc": "1", "value": "Residence"},
                                "Zip": _sanitize(lead_data.get("zip_code", "")),
                                "StateTC": lead_data.get("state", "CA"),
                            },
                            "Phone": {
                                "PhoneTypeCode": {"tc": "1", "value": "Mobile"},
                                "DialNumber": phone_masked,     # Always masked in payload
                            },
                            "EMailAddress": {
                                "AddrLine": email_masked,       # Always masked in payload
                            }
                        }
                    ],
                    "Policy": {
                        "ProductCode": "MORT-PROTECT-TERM",
                        "PolicyStatus": {"tc": "10", "value": "Quote"},
                        "EffectiveDt": now_iso,
                        "Coverage": {
                            "CurrentAmt": lead_data.get("coverage_amount", "250000"),
                            "EstimatedPremiumRange": lead_data.get("pricing_range", ""),
                        }
                    },
                    "OLifEExtension": {
                        "IntermarqLeadScore": lead_data.get("lead_score", 3),
                        "SessionID": lead_data.get("session_id", tx_id),
                        "ChannelSource": "AI-Chatbot",
                        "ComplianceCheck": lead_data.get("compliance", "opa-stub-v1.0"),
                    }
                }
            }
        },
        "_meta": {
            "pii_log": {
                "email_masked": email_masked,
                "phone_masked": phone_masked,
                "note": "Raw PII never stored in this payload or logs."
            }
        }
    }
    return payload
